name: Issue / Bug Report
description: Report an issue
title: "Issue title"
body:
  - type: textarea
    id: issue
    validations:
      required: true
    attributes:
      label: Issue Details
      placeholder: Leave a comment
      