name: Post Template
description: Easy way to create a new post
title: "[Post Template] Don't Submit this issue 😃"
body:
  - type: markdown
    attributes:
      value: |
        This is an issue template to make it easier to setup a post. Copy/paste the below markdown into a new file.

        See the [example post](https://www.vendia.net/blog/typography) & it's [source file](https://github.com/vendia/blog/edit/master/posts/typography.mdx) for markdown formatting tips.

        ## 1. **Click in the textarea below 👇 to copy/paste the template**

  - type: textarea
    id: template
    validations:
      required: true
    attributes:
      label: Post template
      description: copy / paste this into a markdown file!
      placeholder: Tell us what you see!
      value: |
        ---
        title: "Awesome title of this post"
        description: "This is the description of this great post"
        date: "2021-06-08"
        categories:
          - announcements
          - company
        tags:
          - funding
        authors:
          - FirstName LastName
          - SecondAuthor LastName 
        ---

        My post content here in markdown

  - type: markdown
    attributes:
      value: |
        ‎
        ## 2. Add a new post

        After copying the above textarea, click the link below to start a new post.

        **[🚀 Click here to add a new post](https://github.com/vendia/blog/new/master/posts)**

        Remember to name your posts file names like this: `YYYY-MM-DD-blog-post-name.md` with the date prefix.

        **Don't submit this as an issue**. Close this browser tab when you are done.

        Thank you! ❤️

        ───────────────────────────────────────────────────────
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎
        ‎