backend:
  name: github
  repo: vendia/blog
  branch: master
media_folder: public/img # Media files will be stored in the repo under images/uploads
public_folder: img # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select",  multiple: true, options: ["Martina", "Bob", "Steve"]}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}