# Validate markdown content and it's frontmatter
name: validate

on: [push]

env:
  # Show colors for link checker
  FORCE_COLOR: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: bahmutov/npm-install@v1
      with:
        useLockFile: false
    - run: npm t
